"""
Esmerald settings for linezap project.

Generated by 'esmerald createproject' using Esmerald 1.2.5.
"""

import logging
import sys
from typing import Any, List, Optional

from loguru import logger

from esmerald.conf.enums import EnvironmentType
from esmerald.logging import InterceptHandler

from ..settings import AppSettings


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "My application in development mode."
    title: str = "My blog"
    environment: Optional[str] = EnvironmentType.DEVELOPMENT

    def __init__(self, *args: Any, **kwds: Any) -> Any:
        super().__init__(*args, **kwds)
        logging_level = logging.DEBUG if self.debug else logging.INFO
        loggers = ("uvicorn.asgi", "uvicorn.access", "esmerald")
        logging.getLogger().handlers = [InterceptHandler()]
        for logger_name in loggers:
            logging_logger = logging.getLogger(logger_name)
            logging_logger.handlers = [InterceptHandler(level=logging_level)]

        logger.configure(handlers=[{"sink": sys.stderr, "level": logging_level}])
