#!/usr/bin/env python
"""
Generated by 'esmerald createproject' using Esmerald 2.0.5.
"""
import os
import sys

from esmerald import Esmerald, Include, settings
from saffier import Migrate, Registry

database, registry = settings.db_access


def build_path():
    """
    Builds the path of the project and project root.
    """
    SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

    if SITE_ROOT not in sys.path:
        sys.path.append(SITE_ROOT)
        sys.path.append(os.path.join(SITE_ROOT, "apps"))


def get_migrations(app: "Esmerald", registry: "Registry") -> None:
    """
    Activates the migration system of Saffier with Esmerald
    """
    Migrate(app=app, registry=registry)


def get_application():
    """
    This is optional. The function is only used for organisation purposes.
    """
    build_path()

    app = Esmerald(
        routes=[Include(namespace="blog.urls")],
        on_startup=[database.connect],
        on_shutdown=[database.disconnect],
    )

    # Migrations
    get_migrations(app=app, registry=registry)
    return app


app = get_application()
