"""
Esmerald settings for blog project.

Generated by 'esmerald createproject' using Esmerald 2.0.5.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    title: str = "My blog"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = "esmerald-insecure-&amp;p$m*k#%jskm2(k%7^*w1!n6boeo!1+%"