"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from pydantic import BaseModel


class Error(BaseModel):
    detail: str


class PostIn(BaseModel):
    user: int
    content: str


class PostOut(BaseModel):
    id: int
    content: str
    user: str
    created_at: str
