"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from accounts.models import User
from pydantic import BaseModel, field_validator


class Error(BaseModel):
    detail: str


class PostIn(BaseModel):
    user: int
    content: str

    @field_validator("user")
    def validate_user(cls, user: int) -> User:
        """
        Validates and transforms the user
        """
        return User(id=user)


class PostOut(BaseModel):
    id: int
    content: str
    user: str
    created_at: str
