"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from esmerald import Gateway

from .views import create_post, delete_post, posts

route_patterns = [
    Gateway(handler=posts),
    Gateway(handler=create_post),
    Gateway(handler=delete_post),
]
