"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from typing import List

from esmerald import delete, get, post
from esmerald.openapi.datastructures import OpenAPIResponse

from .daos import PostDAO
from .schemas import Error, PostIn, PostOut


@get(
    "/{article_id}",
    tags=["Post"],
    description="Returns all posts of an article",
    summary="Posts of an article",
    responses={
        200: OpenAPIResponse(model=[PostOut]),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def posts(article_id: int) -> List[PostOut]:
    """
    Gets all posts.
    """
    post_dao = PostDAO()
    return await post_dao.get_all(article_id=article_id)


@post(
    "/{article_id}",
    tags=["Post"],
    description="Creates a post for a specific article",
    summary="Create a post of an article",
    responses={
        200: OpenAPIResponse(model=[PostOut]),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def create_post(data: PostIn, article_id: int) -> PostOut:
    """
    Creates a post for a specfic article.
    """
    posts_dao = PostDAO()
    return await posts_dao.create(article_id=article_id, **data.model_dump())


@delete(
    "/{article_id}/{post_id}",
    tags=["Post"],
    description="Deletes a post from the article",
    summary="Deletes a post",
    responses={
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def delete_post(article_id: int, post_id: int) -> None:
    """
    Deletes a post from an article
    """
    posts_dao = PostDAO()
    await posts_dao.delete(obj_id=post_id, article_id=article_id)
