"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from typing import List

from esmerald import delete, get, post, put
from esmerald.openapi.datastructures import OpenAPIResponse

from .daos import PostDAO
from .schemas import Error, PostIn, PostOut


@get(
    "/posts/{article_id}",
    tags=["Post"],
    description="Returns all posts of an article",
    summary="Posts of an article",
    responses={
        200: OpenAPIResponse(model=[PostOut]),
        400: OpenAPIResponse(model=Error, description="Bad response"),
    },
)
async def posts(article_id: int) -> List[PostOut]:
    """
    Gets all posts.
    """
    post_dao = PostDAO()
    return await post_dao.get_all(article_id=article_id)
