"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from typing import Union

from accounts.models import User
from pydantic import BaseModel, field_validator


class Error(BaseModel):
    detail: str


class ArticleIn(BaseModel):
    user: int
    title: str
    content: str

    @field_validator("user")
    def validate_user(cls, user: int) -> User:
        """
        Validates and transforms the user
        """
        return User(id=user)


class ArticleUpdate(BaseModel):
    title: str
    content: Union[str, None] = None


class ArticleOut(BaseModel):
    id: int
    user: int
    title: str
    content: str
    created_at: str
    updated_at: str
