"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from esmerald import Gateway

from .views import article, articles, create_article, delete_article, update_article

route_patterns = [
    Gateway(handler=articles),
    Gateway(handler=article),
    Gateway(handler=create_article),
    Gateway(handler=update_article),
    Gateway(handler=delete_article),
]
