"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from typing import Any, Dict, Optional

import slugify
from pydantic import BaseModel, model_validator


class Error(BaseModel):
    detail: str


class UserIn(BaseModel):
    """
    Validates the user information.
    """

    first_name: str
    last_name: str
    email: str
    username: Optional[str]
    is_superuser: bool = False
    password: str
    retype_password: str

    @model_validator(mode="before")
    def validate_user_data(cls, values) -> Dict[str, Any]:
        """
        Validates the user in data.
        """
        password = values.get("password", None)
        username = values.get("username", None)
        retype_password = values.get("retype_password", None)

        if password != retype_password:
            raise ValueError("The passwords do not match.")

        if not username:
            username = f"{values['first_name']-{values['last_name']-{values['email']}}}"
            username = slugify.slugify(username)
            values["username"] = username

        return values


class UserOut(BaseModel):
    """
    The information being sent back to the client.
    """

    id: int
    first_name: str
    last_name: str
    email: str
    username: Optional[str]
    is_superuser: bool
