"""
Generated by 'esmerald createapp' using Esmerald 2.0.5.
"""
from esmerald import Gateway

from .views import create, delete_user, user, users

route_patterns = [
    Gateway(handler=users),
    Gateway(handler=user),
    Gateway(handler=create),
    Gateway(handler=delete_user),
]
